package alex;

public enum ClaseLexica {
 BEGIN, END, DECLARE, VAR, CLASS, FUNCTION,
 CCLASS, PUBLIC, PRIVATE, 
 IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, FOR, ENDFOR, 
 FOREACH, IN, ENDFOREACH, REPEAT, UNTIL, ENDREPEAT, 
 SWITCH, CASE, DEFAULT, ENDSWITCH, RETURN,
 INT, FLOAT, CHAR, STRING, BOOL, 
 ID, IID, ENT, REAL, BOOLEAN, VCHAR, VSTRING, 
 SUMA, RESTA, MULT, DIV, DIVENT, MOD, EXP, AND, OR, NOT,
 PAP, PCIERRE, LAP, LCIERRE, OPIGUAL, OPDISTINTO, MENOR, MENORIG, 
 MAYOR, MAYORIG, 
 IGUAL, COMA, PUNTOCOMA
 , EOF
}
