
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 05 18:27:12 CEST 2015
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int IID = 37;
  public static final int FUNCTION = 7;
  public static final int VSTRING = 42;
  public static final int DIVENT = 47;
  public static final int MULT = 45;
  public static final int CHAR = 33;
  public static final int PCIERRE = 54;
  public static final int LCIERRE = 56;
  public static final int LAP = 55;
  public static final int CASE = 27;
  public static final int RESTA = 44;
  public static final int PRIVATE = 10;
  public static final int REPEAT = 23;
  public static final int INT = 31;
  public static final int PUNTOCOMA = 65;
  public static final int FOR = 18;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int IGUAL = 63;
  public static final int ENDSWITCH = 29;
  public static final int OR = 51;
  public static final int IN = 21;
  public static final int BOOL = 35;
  public static final int CLASS = 6;
  public static final int DIV = 46;
  public static final int BEGIN = 2;
  public static final int ENDFOR = 19;
  public static final int UNTIL = 24;
  public static final int SUMA = 43;
  public static final int IF = 11;
  public static final int EXP = 49;
  public static final int ID = 36;
  public static final int ENDWHILE = 17;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int OPDISTINTO = 58;
  public static final int error = 1;
  public static final int COMA = 64;
  public static final int VCHAR = 41;
  public static final int ENDFOREACH = 22;
  public static final int MENOR = 59;
  public static final int MOD = 48;
  public static final int DECLARE = 4;
  public static final int SWITCH = 26;
  public static final int MAYOR = 61;
  public static final int REAL = 39;
  public static final int ENT = 38;
  public static final int PAP = 53;
  public static final int FOREACH = 20;
  public static final int ENDIF = 14;
  public static final int ELSE = 13;
  public static final int MAYORIG = 62;
  public static final int WHILE = 15;
  public static final int OPIGUAL = 57;
  public static final int DEFAULT = 28;
  public static final int FLOAT = 32;
  public static final int PUBLIC = 9;
  public static final int MENORIG = 60;
  public static final int THEN = 12;
  public static final int END = 3;
  public static final int ENDREPEAT = 25;
  public static final int STRING = 34;
  public static final int CCLASS = 8;
  public static final int VAR = 5;
  public static final int DO = 16;
}

